----------------------------------------------------------------------------------------
-- // Please do not edit this file, make changes through the in-game configuration // --
----------------------------------------------------------------------------------------
-- Scoreboard version --
------------------------
SD_SCOREBOARD_GMS.Ver = "1.0.5"
------------------
-- First config --
------------------
SD_SCOREBOARD_GMS.Config = {
	hostName = GetHostName(),

	boolean = {
		groupUnderName = false,
		jobsUnderName = false,
		ping = true,
		deaths = true,
		kills = true,

		plyTime = false,
		sessionTime = false,

		ulx = true,
		fadmin = true
	},

	sortBy = "ping",
	categoriesBy = "ByGroup",

	groups = {},
	commands = {},
	links = {},
	hide = {}
}