----------------------------------------------------------------------------------------
-- // Please do not edit this file, make changes through the in-game configuration // --
----------------------------------------------------------------------------------------
-- Scoreboard version --
------------------------
SD_SCOREBOARD_GMS.Ver = "1.1.5"
-----------
-- fonts --
-----------
surface.CreateFont( "sd_scoreboard_14_100", { font = "Roboto", extended  = true, antialias = true, shadow = false, weight = 500, size = 18}) 
surface.CreateFont( "sd_scoreboard_16_100", { font = "Roboto", extended  = true, antialias = true, shadow = false, weight = 500, size = 20})
surface.CreateFont( "sd_scoreboard_25_100", { font = "Roboto", extended  = true, antialias = true, shadow = false, weight = 500, size = 25})
surface.CreateFont( "sd_scoreboard_20_100", { font = "Roboto", extended  = true, antialias = true, shadow = false, weight = 500, size = 20})
-------------
-- ConVars --
-------------
CreateConVar("sd_scoreboard_blur", 1, FCVAR_ARCHIVE, "Background blur")
CreateConVar("sd_scoreboard_fullscreen", 0, FCVAR_ARCHIVE, "Fullscreen")
CreateConVar("sd_scoreboard_scheme", 2, FCVAR_ARCHIVE, "Color scheme")
CreateConVar("sd_scoreboard_language", 1, FCVAR_ARCHIVE, "Language")
----------
-- Tabs --												
----------
SD_SCOREBOARD_GMS.Tabs = {
	{
		name 	= "players",
		vgui 	= "sd_scoreboard_players",				
		color 	= Color(100,180,100),
		icon 	= "players",

	},
	{
		name 	= "options",
		vgui 	= "sd_scoreboard_settings",				
		color 	= Color(100,180,180),
		icon 	= "options",
	},
	{
		name 	= "admSettings",
		vgui 	= "sd_scoreboard_admin_settings",		
		color 	= Color(100,180,180),
		icon 	= "staff",
	},
}
---------------------
-- Main data table --
---------------------
SD_SCOREBOARD_GMS.ServerConfig = SD_SCOREBOARD_GMS.ServerConfig or {hostName = "", sortBy = "", categoriesBy = "", boolean = {}, groups = {}, commands = {}, links = {}, hide = {}}
------------------------------------
-- Add booleans to admin settings --
------------------------------------
SD_SCOREBOARD_GMS.Config.boolean = {}

SD_SCOREBOARD_GMS.AddBool("adminMods", "adminModsDesc", "FAdmin", "DarkRP", "fadmin")
SD_SCOREBOARD_GMS.AddBool("adminMods", "adminModsDesc", "ULX", "Other", "ulx")
SD_SCOREBOARD_GMS.AddBool("adminMods", "adminModsDesc", "xAdmin", "Other", "xadmin")
SD_SCOREBOARD_GMS.AddBool("adminMods", "adminModsDesc", "sAdmin", "Other", "sadmin")
SD_SCOREBOARD_GMS.AddBool("adminMods", "adminModsDesc", "SAM Admin Mod", "Other", "sam")

SD_SCOREBOARD_GMS.AddBool("columnsOnPly", "columnsOnPlyDesc", "jobsUnderName", "DarkRP", "jobsUnderName")

SD_SCOREBOARD_GMS.AddBool("columnsOnPly", "columnsOnPlyDesc", "groupUnderName", "Common", "groupUnderName")
SD_SCOREBOARD_GMS.AddBool("columnsOnPly", "columnsOnPlyDesc", "ping", "Common", "ping")
SD_SCOREBOARD_GMS.AddBool("columnsOnPly", "columnsOnPlyDesc", "deaths", "Common", "deaths")
SD_SCOREBOARD_GMS.AddBool("columnsOnPly", "columnsOnPlyDesc", "kills", "Common", "kills")

SD_SCOREBOARD_GMS.AddBool("columnsOnPly", "columnsOnPlyDesc", "sessionTime", "ULX - Utime", "sessionTime")
SD_SCOREBOARD_GMS.AddBool("columnsOnPly", "columnsOnPlyDesc", "plyTime", "ULX - Utime", "plyTime")
-------------
-- columns --
-------------
SD_SCOREBOARD_GMS.Columns = {}

SD_SCOREBOARD_GMS.AddColumn("plyName", LEFT, TEXT_ALIGN_LEFT, 150, function(ply)
	if !IsValid(ply) then return end

	local boolean = SD_SCOREBOARD_GMS.ServerConfig.boolean or {}
	local subText = boolean.jobsUnderName and team.GetName(ply:Team()) or boolean.groupUnderName and ply:GetUserGroup() or false

	return ply:Nick(), subText
end)

SD_SCOREBOARD_GMS.AddColumn("plyTime", RIGHT, TEXT_ALIGN_CENTER, 180, function(ply)
	if !IsValid(ply) then return end

	local boolean = SD_SCOREBOARD_GMS.ServerConfig.boolean or {}
	if not ply.GetUTime then return "Utime not installed", false end

	local totalTime = ply:GetUTime() + CurTime() - ply:GetUTimeStart()
	local sessionTime = boolean.sessionTime and CurTime() - ply:GetUTimeStart() or false

	return SD_SCOREBOARD_GMS.GetTime(totalTime), sessionTime and SD_SCOREBOARD_GMS.GetTime(sessionTime) or false, totalTime
end)

SD_SCOREBOARD_GMS.AddColumn("kills", RIGHT, TEXT_ALIGN_CENTER, 60, function(ply)
	if !IsValid(ply) then return end

	local boolean = SD_SCOREBOARD_GMS.ServerConfig.boolean or {}
	return boolean.kills and ply:Frags() or false, false 
end)

SD_SCOREBOARD_GMS.AddColumn("deaths", RIGHT, TEXT_ALIGN_CENTER, 60, function(ply)
	if !IsValid(ply) then return end

	local boolean = SD_SCOREBOARD_GMS.ServerConfig.boolean or {}
	return boolean.deaths and ply:Deaths() or false, false 
end)

SD_SCOREBOARD_GMS.AddColumn("ping", RIGHT, TEXT_ALIGN_CENTER, 60, function(ply)
	if !IsValid(ply) then return end
	
	local boolean = SD_SCOREBOARD_GMS.ServerConfig.boolean or {}
	return boolean.ping and ply:Ping() or false, false 
end)
-----------------------------------------------
-- Set color scheme and language from conVar --
-----------------------------------------------
SD_SCOREBOARD_GMS.SetColorScheme(GetConVarNumber("sd_scoreboard_scheme"))
SD_SCOREBOARD_GMS.SetLanguage(GetConVarNumber("sd_scoreboard_language"))
--------------------------------------------------
-- set blur and fullscreen settings from conVar --
--------------------------------------------------
SD_SCOREBOARD_GMS.BackgroundBlur = GetConVarNumber("sd_scoreboard_blur")
SD_SCOREBOARD_GMS.fullScreen = GetConVarNumber("sd_scoreboard_fullscreen")