
local function AddPlayerModel( name, model )

    list.Set( "PlayerOptionsModel", name, model )
    player_manager.AddValidModel( name, model )
	player_manager.AddValidHands( "Metro-Male-1", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
	player_manager.AddValidHands( "Metro-Male-2", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
	player_manager.AddValidHands( "Metro-Male-3", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
	player_manager.AddValidHands( "Metro-Male-4", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
	player_manager.AddValidHands( "Metro-Male-5", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
	player_manager.AddValidHands( "Metro-Male-6", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
	player_manager.AddValidHands( "Metro-Male-7", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
	player_manager.AddValidHands( "Metro-Male-8", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
	player_manager.AddValidHands( "Metro-Male-9", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
	player_manager.AddValidHands( "Metro-Female-1", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
	player_manager.AddValidHands( "Metro-Female-2", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
	player_manager.AddValidHands( "Metro-Female-3", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
	player_manager.AddValidHands( "Metro-Female-4", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
	player_manager.AddValidHands( "Metro-Female-5", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
	player_manager.AddValidHands( "Metro-Female-6", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
	player_manager.AddValidHands( "Metro-Extra-1", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
	player_manager.AddValidHands( "Metro-Extra-2", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
	player_manager.AddValidHands( "Metro-Extra-3", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
	player_manager.AddValidHands( "Metro-Extra-4", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
	player_manager.AddValidHands( "Metro-Extra-5", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
	player_manager.AddValidHands( "Metro-Extra-6", "models/half-dead/metroll/c_arms_male1.mdl", 0, "00000000" )
    
end

AddPlayerModel( "Metro-Male-1", "models/half-dead/metroll/m1b1.mdl" )
AddPlayerModel( "Metro-Male-2", "models/half-dead/metroll/m2b1.mdl" )
AddPlayerModel( "Metro-Male-3", "models/half-dead/metroll/m4b1.mdl" )
AddPlayerModel( "Metro-Male-4", "models/half-dead/metroll/m5b1.mdl" )
AddPlayerModel( "Metro-Male-5", "models/half-dead/metroll/m6b1.mdl" )
AddPlayerModel( "Metro-Male-6", "models/half-dead/metroll/m7b1.mdl" )
AddPlayerModel( "Metro-Male-7", "models/half-dead/metroll/m8b1.mdl" )
AddPlayerModel( "Metro-Male-8", "models/half-dead/metroll/m9b1.mdl" )
AddPlayerModel( "Metro-Male-9", "models/half-dead/metroll/m1b1.mdl" )
AddPlayerModel( "Metro-Female-1", "models/half-dead/metroll/f1b1.mdl" )
AddPlayerModel( "Metro-Female-2", "models/half-dead/metroll/f2b1.mdl" )
AddPlayerModel( "Metro-Female-3", "models/half-dead/metroll/f3b1.mdl" )
AddPlayerModel( "Metro-Female-4", "models/half-dead/metroll/f4b1.mdl" )
AddPlayerModel( "Metro-Female-5", "models/half-dead/metroll/f6b1.mdl" )
AddPlayerModel( "Metro-Female-6", "models/half-dead/metroll/f7b1.mdl" )
AddPlayerModel( "Metro-Extra-1", "models/half-dead/metroll/a1b1.mdl" )
AddPlayerModel( "Metro-Extra-2", "models/half-dead/metroll/a2b1.mdl" )
AddPlayerModel( "Metro-Extra-3", "models/half-dead/metroll/a3b1.mdl" )
AddPlayerModel( "Metro-Extra-4", "models/half-dead/metroll/a4b1.mdl" )
AddPlayerModel( "Metro-Extra-5", "models/half-dead/metroll/a5b1.mdl" )
AddPlayerModel( "Metro-Extra-6", "models/half-dead/metroll/a6b1.mdl" )
